### ISSUE TITLE
Development of Singularity Container

### ISSUE THREAD

**Issue by clmcnabb** [pGarciaS/PREEMACS#1]
Hello,

I am a student at the University of Utah currently working with macaque image processing and building head models, and my lab was interested in using your program on our CHPC cluster. Due to the dependencies, our CHPC would need your software to be implemented in a singularity container. I've attempted building one myself, but was unsuccessful. Our IT offered to help, but they were wondering if it would be possible to obtain a copy of where the container is at currently in order to not start from scratch. Please let me know if this would be possible. Thank you!

**Comment by kilimanjaro2** [comment]
Hello @nabbers92 . I was busy for a while and did not actually clean up some things in the repo. I'll work on it over the weekend and send you something cleaner on Monday. Hope this helps!

**Comment by clmcnabb** [comment]
Hey @kilimanjaro2, I just wanted to check in and see if you had something you would be able to send me yet. Thank you again!
